[book]
authors = ["Duane Bester"]
language = "en"
multilingual = false
src = "src"
title = "From Zero to IoT"

[output.html]
git-repository-url = "https://github.com/duanebester/iot-rs"

[output.html.playground]
editable = true